---
Name: nswdpc-authentication-boilerplate-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'mfa_help': NSWDPC\Authentication\Controllers\AuthenticationHelpController
